spring:
  application:
    name: barbershop-api

  datasource:
    url: jdbc:postgresql://localhost:5433/barbershop_db
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8080

